// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onbyfmaxiswxxymyfyzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYnlmbWF4aXN3eHh5bXlmeXppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzk0NTIsImV4cCI6MjA3MjgxNTQ1Mn0.lSL60jMZ0xQuIM2iHZk7cDCjpsTiJEgjEFGpwF8qJ5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});